### ISSUE TITLE
Nested YAML variables overwriting parent array

### ISSUE THREAD

**Issue by cossssmin** [tighten/jigsaw#291]
I have a situation where I need to overwrite a single nested key/value pair inside an array, with YAML Front Matter. For example, consider this array in `config.php`:

```php
return [
    'foo' => [
        'bar' => true,
        'baz' => 'something',
    ],
   // other config keys
];
```

Using YAML, I wanted to set `baz` to something else for a certain page:

```markdown
---
extends: _layouts.master
section: content
foo:
  baz: 'something else'
---
```
Doing this currently replaces the/creates a new `foo` array. So this:

```blade
<pre>
    <code>{{ var_dump($page->foo) }}</code>
</pre>
```

... will output this:

```php
object(TightenCo\Jigsaw\IterableObject)#390 (1) {
  ["items":protected]=>
  array(1) {
    ["baz"]=>
    string(21) "something else"
  }
}
```

If possible, it would be great if Jigsaw would merge in what you specify in YAML, instead of replacing the/creating a new `foo`. Hope this makes sense.

Thanks!

**Comment by hellocosmin** [comment]
Also worth mentioning is the concept of [YAML Anchors, References, and Extends](https://blog.daemonl.com/2016/02/yaml.html). 

However, I think this would get pretty tedious to have to write all the time, so maybe just merging nested variables with the parent by default would be much easier from a user perspective (?)
