### ISSUE TITLE
Rebuild not triggered if you create a new file while Webpack is watching (v1.3.0)

### ISSUE THREAD

**Issue by cossssmin** [tighten/jigsaw#301]
In v1.3.0, while `watch`ing files, if I create a new `.md` file it's not being picked up - a rebuild is not triggered. 

Looks like `watch`ed files need to exist _before_ runnning `npm run watch`, otherwise it just won't trigger a rebuild and browser refresh.

Using Collections, so I have the `.md` files like this inside the `source` directory:

```
├───_docs
│   └───getting-started
│           introduction.md
```

If, while Webpack is watching files, I create `installation.md` inside the `getting-started` directory, nothing happens. Not even if I add some text to it and save it.

I need to either exit and `npm run watch` again, or just save an existing file, in order for this new one to be picked up.

This used to work fine pre-1.3.0, so I wonder if it has anything to do with `extra-watch-webpack-plugin`?

My `webpack.mix.js` file:

```js
let mix = require('laravel-mix');
let tailwind = require('tailwindcss');
let build = require('./tasks/build.js');
require('laravel-mix-purgecss');

mix.disableSuccessNotifications();
mix.setPublicPath('source/assets/');
mix.webpackConfig({
  plugins: [
    build.jigsaw,
    build.browserSync(),
    build.watch(['source/**/*.md', 'source/**/*.php', 'source/_assets/**/*', '!source/**/_tmp/*', '!source/assets/**/*']),
  ]
});

mix.options({
    processCssUrls: false,
    postCss: [
      require('postcss-import'),
      require('postcss-nested'),
      tailwind('tailwind.js'),
    ]
  })
  .postCss('source/_assets/css/app.css', 'css')
  .js('source/_assets/js/app.js', 'js')
  .purgeCss({
    folders: ['source'],
  })
  .version();
```

**Comment by damiani** [comment]
Good catch, looking into this now...

**Comment by godbout** [comment]
Having the same issue as @cossssmin, and doing the same trick to make it work :D
But the workflow feels a bit broken, yes.

**Comment by drbe4t** [comment]
Hey guys I'm having the same issue but I'm not quite sure what you changed your webpack file to get it to rebuild properly.

**Comment by bakerkretzmar** [comment]
Closing this as I believe it's solved/invalidated by the [`laravel-mix-jigsaw`](https://github.com/tighten/laravel-mix-jigsaw) plugin, v2 of which can watch for both file changes and creation in _almost_ all source paths. Feel free to comment here or open an issue in that repo if this is a still a problem!
