### ISSUE TITLE
writeSourceFile should not override the source file

### ISSUE THREAD

**Issue by stancl** [tighten/jigsaw#328]
It would be cool if there was a method like writeSourceFile() which would let you modify the contents for the build, but not override the actual source file.

I guess there could be some temporary file content storage and jigsaw could check for every file if it is in that storage before loading it from the source directory.

**Comment by damiani** [comment]
This would add a fair amount of overhead to all builds, particularly on larger sites, so I don't think we'll be adding this at the moment. In v2, we're considering adding more a more robust way to hook into (and modify) a source file during the build, before output, but I don't think that change will be tenable in the current version.
