### ISSUE TITLE
Adding support for custom collection directories

### ISSUE THREAD

**Issue by ryangjchandler** [tighten/jigsaw#448]
On larger projects, I can image the `source` folder getting quite out of hand. One way to tackle this would be adding support for custom collection directories.

For example, if I have a `posts` collection I could specify a `sourcePath` key in the collection configuration array and point it to a custom `./content/posts` path where I store my Markdown or Blade files.

I can't see the implementation being too difficult, since the path is only used in a couple of places.

What do others think? If people are interested, I'll throw in a PR for this.

**Comment by lokmanm** [comment]
Plus one for this one. I already have a large project that I'm working on with Jigsaw and the source folder is filled and it's really hard to navigate.

**Comment by damiani** [comment]
Agreed. I looked into this yesterday, and it's a little bit involved ... but this is definitely worth doing.

**Comment by bakerkretzmar** [comment]
Closing this but @ryangjchandler we're definitely still open to a PR! I'll also note that you can already customize the source path, for example to put it in a `content` directory instead, [by adding a `build` array to your configuration](https://jigsaw.tighten.co/docs/deploying-your-site/#changing-the-source-and-destination-directories) with `source` and/or `destination` keys pointing to other paths. If you want to store your views somewhere separate from the `content` directory, #564 would make that possible too.
