### ISSUE TITLE
A weird issue with OptimizeCssAssetsWebpackPlugin

### ISSUE THREAD

**Issue by aligajani** [tighten/jigsaw#481]
I have this exact same setup on a Laravel app with Mix. Same files, copy pasted over to Jigsaw and I run into this:
`npm run production`.

I literally have the same SCSS files in another project and they compile to build fine. Note, that project doesn't use Jigsaw.

```
92% chunk asset optimization OptimizeCssAssetsWebpackPluginJisonParserError: Parse error on line 1: 
1.5em + 1.25rem2px
---------^
Expecting end of input, "RPAREN", "ADD", "SUB", "MUL", "DIV", got unexpected "UNKNOWN_DIMENSION"
    at /Users/aligajani/Sites/shadow-website/css/theme.css:6717:3

```

**Comment by bakerkretzmar** [comment]
@aligajani are your 2 projects on the same Laravel Mix version? Can you share the block of your source CSS that this error is related to? Thanks.
