### ISSUE TITLE
Using composer package

### ISSUE THREAD

**Issue by gwleuverink** [tighten/jigsaw#499]
I have this [tiny composer package ](https://github.com/gwleuverink/blade-shape-divider) which is just a blade component that spits out an svg. 

It makes sense that the service provider doesn't register automatically. Is there any way to do so manually? Since the package only generates some static markup It should work in a statically generated site. 

Thanks for your help!

**Comment by bakerkretzmar** [comment]
@gwleuverink great question, and cool package! The short answer is yes this is possible, but it takes a bit of work. The long answer:

Jigsaw doesn't include the `view()` helper function, which your package uses, so I had to re-implement it in `bootstrap.php`:

```php
<?php

use Illuminate\Container\Container;
use Illuminate\View\Factory;

function view($view = null, $data = [], $mergeData = [])
{
    $factory = Container::getInstance()[Factory::class];

    if (func_num_args() === 0) {
        return $factory;
    }

    return $factory->make($view, $data, $mergeData);
}

$container['view']->addNamespace('shape-divider', __DIR__ . '/vendor/leuverink/blade-shape-divider/components');
```

The only line I had to change inside the `view()` function was the first one (there's no `app()` helper either):

```diff
- $factory = app(ViewFactory::class);
+ $factory = Container::getInstance()[Factory::class];
```

Then I added the view namespace (copied from your service provider) and just updated the path:

```php
$container['view']->addNamespace('shape-divider', __DIR__ . '/vendor/leuverink/blade-shape-divider/components');
```

Finally, [following the docs](https://jigsaw.tighten.co/docs/content-blade/#extending-blade-with-custom-directives), I created a `blade.php` file in the root of the site to register the component:

```php
<?php

use Leuverink\BladeShapeDivider\ShapeDivider;

$bladeCompiler->component('shape-divider', ShapeDivider::class);
```

And it works!

<img width="1000" alt="Screen Shot 2020-10-02 at 10 23 47 AM" src="https://user-images.githubusercontent.com/18192441/94934224-72f37f80-0499-11eb-9102-845690ae98bf.png">

Let me know if you have any other questions! I'm sure there are ways we could make this easier 😄

**Comment by gwleuverink** [comment]
Hi @bakerkretzmar. Thanks for your comprehensive explanation! I’ll link to this issue in the readme for now while I ponder a solution on my side.
