### ISSUE TITLE
returns error when running jigsaw init blog

### ISSUE THREAD

**Issue by AjithLalps** [tighten/jigsaw#500]
Returns error `The 'tightenco/jigsaw-blog-template' preset could not be found.` when running `jigsaw init blog`. I think its because of the `recent username update`.

**Comment by damiani** [comment]
While the GitHub username changed, the Composer namespace is still `tightenco`, so there must be something else going on here. `jigsaw init blog` is working fine for me on a fresh install of Jigsaw; are you running `jigsaw init` on a fresh project, or an existing one?

**Comment by AjithLalps** [comment]
jigsaw init on fresh project

**Comment by AjithLalps** [comment]
It is working now.
