### ISSUE TITLE
To be able to force overwriting the existing folder when running the build command

### ISSUE THREAD

**Issue by khalyomede** [tighten/jigsaw#508]
## Description

I am using composer script to simplify building and serving my project. I would like to be able to automatically answer "yes" when the build commands asks if I want to overwrite an existing folder.

## Proposal

To have a new option, `--yes` (or `-y`), to be able to automatically pass the question if the folder already exist before building the static site.

```bash
vendor/bin/jigsaw build --yes
```

## Additional context

I am using compser script as following:

```json
{
  "scripts": {
    "build": "jigsaw build",
  }
}
```

**Comment by bakerkretzmar** [comment]
You can pass `--quiet` (or `-q`) and Jigsaw will suppress that prompt and overwrite the existing folder. That will also hide all its output—if you want to still see Jigsaw's build time and completed message in the console, you can change your Composer script to `echo 'y' | jigsaw build` which will answer the prompt for you.

The prompt only appears if you've customized the `build.destination` config value, so it also won't ask for confirmation at all if your build destination starts with `build_`.

Let us know if that works!

**Comment by khalyomede** [comment]
Thank you, it worked like a charm!
