### ISSUE TITLE
Github Pages Deploy Issue

### ISSUE THREAD

**Issue by nasirkhan** [tighten/jigsaw#515]
I created Jigsaw site and I followed the [Deploy Doc](https://jigsaw.tighten.co/docs/deploying-your-site/) to deploy as Github Pages. But the url paths are not being configured properly. 

My github page site is at https://github.com/nasirkhan/onlinequiz.io and the issue i found that all the urls are not working. The css is linked as `https://nasirkhan.github.io/assets/build/css/main.css` where as it should be `https://nasirkhan.github.io/onlinequiz.io/assets/build/css/main.css`

Can you please show me a doc where I can find the instructions to configure the site properly

**Comment by bakerkretzmar** [comment]
Can you try adjusting the build output to actually include a folder called `onlinequiz.io`? Take a look at the [Changing the source and destination directories](https://jigsaw.tighten.co/docs/deploying-your-site/#changing-the-source-and-destination-directories) section of those docs.

It sounds like right now you're making the contents of `build_production` your site root, so I think what you need to do is instead of outputting the built files directly into `build_production`, output them into `build_production/onlinequiz.io`. Keep your git setup the same, so that your site root contains just an `onlinequiz.io` folder containing your site.

Let me know if that makes sense and if it works!

**Comment by nasirkhan** [comment]
Thanks for your response. 

Actually i want to make the site available at https://nasirkhan.github.com/onlinequiz.io and here i will use the github pages to do that. 

I will also want to show the same content form `onlinequiz.io` but i will just upload the contents for that domain. But first I need to show the site from https://nasirkhan.github.com/onlinequiz.io

I added a new build path but it does not solve the issue.

I saw that the links to CSS is added as https://nasirkhan.github.io/assets/build/css/main.css but is should be https://nasirkhan.github.io/onlinequiz.io/assets/build/css/main.css

**Comment by nasirkhan** [comment]
I added a `Site Variable` to store the Github Project path and used that with the CSS and JS asset path. So now the these files are loading. But some links and images are also referring the domain root which is  https://nasirkhan.github.com/ . Links on the list pages (Blog, Home) pages are just working fine from the beginning but the navs are not. 

I think Jigsaw is configured in a way that everyone need to deploy the site on a domain root. But for me or any Github Pages the case is not the same. All GIthub page sites will be displayed from a directory. So is it possible to prepare a setup to address this issue?

**Comment by bakerkretzmar** [comment]
Okay I see what's happening. Jigsaw uses mostly relative links internally, so something like `/app.js` in your case resolves to `https://nasirkhan.github.io/app.js`. You'll need to use the complete, absolute URL for things like assets and nav links.

I forked your site and it works great with the production `baseUrl` set correctly, no special build destination, and no `github_project`—just put `{{ trim($page->baseUrl, '/') }}` in front of the URLs that aren't working.

See https://github.com/tighten/jigsaw/issues/254#issuecomment-415583895 and https://github.com/tighten/jigsaw/issues/442#issuecomment-612903405.

**Comment by nasirkhan** [comment]
Thanks for the help. 

From the comments you referred, i found that some other also have the similar issue and they are reporting for years. Isn't it better to solve permanently and update the base template? like we can add the base url on all the places for image, css and js.

created a new helper "asset" to add the baseUrl with the path. This solved the blade file link issue. 

But there are error in the Vue files. If you visit https://nasirkhan.github.io/onlinequiz.io/ you will find the error in the developer console. Do you have any suggestions to fix those?

**Comment by bakerkretzmar** [comment]
Yeah I agree this should probably be updated in the base templates.

I believe the Vue errors are being caused by the same issue, it looks like the Fuse search integration is looking for an `index.json` file at the site root, so you'll probably need to update the `Search.vue` component to use the correct URL.

**Comment by nasirkhan** [comment]
I can update the path on the vue files, and mention the full base url there. But is it the right/ best way to do so?

Jigsaw it here for a decent amount of time, but i think i am the first one who is trying to host the site from the Github Pages, otherwise these issues would have solved.

**Comment by bakerkretzmar** [comment]
> I can update the path on the vue files, and mention the full base url there. But is it the right/ best way to do so?

Yes, for example just change `/index.json` to `/onlinequiz.io/index.json`.

> Jigsaw it here for a decent amount of time, but i think i am the first one who is trying to host the site from the Github Pages, otherwise these issues would have solved.

I think your particular use case where the site is in a subdirectory is pretty uncommon, yeah. I know GitHub Pages is popular, but I think most people probably use a custom domain or use the root `username.github.io` site with no `/projectname` after.

**Comment by nasirkhan** [comment]
I may made mistake but this does not solve the issue for me. But thanks for your help.

I think this issue should remain open, as Jigsaw is not ready to be used as Github pages yet.
