### ISSUE TITLE
Markdown files are published even though they are not inside navigation

### ISSUE THREAD

**Issue by stevebauman** [tighten/jigsaw#517]
I'm using the [jigsaw-docs-template](https://github.com/tighten/jigsaw-docs-template) for my site [LdapRecord.com](LdapRecord.com). I have just separated the site to use multiple versions (ran into the same issues as @stancl - https://github.com/tighten/jigsaw-docs-template/issues/31).

Jigsaw appears to be publishing *all* of the pages inside of my `source/docs` folder, even though the files are not specified in Jigsaw's configuration file.

I have my documentation stored with the following pattern:

```
source/docs/core/v1/*.md
source/docs/core/v2/*.md

source/docs/laravel/v1/*.md
source/docs/laravel/v2/*.md
```

Here's a snippet of my `config.php`:

```php
<?php

return [
    '...',

    'navigation' => [
        'core' => [
            'v1' => require_once('versions/core/v1/navigation.php'),
        ],
        'laravel' => [
            'v1' => require_once('versions/laravel/v1/navigation.php'),
        ],
    ],

    '...',
];
```

And a snippet of my `navigation.php`:

```php
<?php

return [
    'Introduction' => [
        'children' => [
            'Quickstart' => 'docs/core/v1/quickstart',
            'Overview' => 'docs/core/v1',
            'Installation' => 'docs/core/v1/installation',
            'Configuration' => 'docs/core/v1/configuration',
            'Connections' => 'docs/core/v1/connections',
        ],
    ],

    '...',
];
```

Though Jigsaw appears to still process both the `core/v2` and `laravel/v2` folders contents, as they are output in my `build_*` folders:

<img width="254" alt="Screen Shot 2020-11-09 at 12 33 52 PM" src="https://user-images.githubusercontent.com/6421846/98575967-dab29c80-2287-11eb-9b12-8f624a9a0bea.png">

Is there some sort of mapping that is done that processes all of the files regardless of being specified or not? I tried digging in the source quite deep, but I'm stuck. I don't know why the files are being published.

Any insight would be greatly appreciated! ❤️

**Comment by damiani** [comment]
Jigsaw will process any file/directory that isn't prefixed with an underscore. If you want to exclude all the `v2` files, you could change their directories to `_v2`.

**Comment by stevebauman** [comment]
Ohhh okay thanks @damiani! I see this already exists in the documentation:

https://jigsaw.tighten.co/docs/content-blade/#preventing-layouts-&-partials-from-rendering

But of course, I didn't take the time to read it 😞, sorry about that!

I really appreciate your time!

**Comment by damiani** [comment]
No worries at all, good luck with your project!
