### ISSUE TITLE
Map collection to different source

### ISSUE THREAD

**Issue by piercemcgeough** [tighten/jigsaw#518]
Is it possible to have something like this where I can split my posts and featured posts but from the same collection without having separate folders?

```
'collections' => [
    'posts' => [
        'sort' => '-published',
        'filter' => function ($item) {
            return ! $item->draft && ! $item->featured;
        }
    ],

    'featuredPosts' => [
        'path' => 'posts',
        'filter' => function ($item) {
            return ! $item->draft && $item->featured;
        }
    ]
],
```

**Comment by damiani** [comment]
No, but you can always call Laravel collection methods directly in your views, to do something like:

```
@foreach ($posts->where('featured')->where('draft', false) as $featuredPost)
...
```

What are you trying to accomplish?

**Comment by piercemcgeough** [comment]
I was looking to get 3 featured posts from the posts based on a boolean. Then I could loop over those 3 and then a regular posts list below.

**Comment by damiani** [comment]
Great, you can do that in a view by treating your posts as a regular Laravel collection. Check out how it's done on the index page of the Jigsaw blog template: https://github.com/tighten/jigsaw-blog-template/blob/main/source/index.blade.php
