### ISSUE TITLE
PHP8 forces to use version 1.0.9

### ISSUE THREAD

**Issue by milon** [tighten/jigsaw#521]
I was in the latest version of jigsaw. As I upgrade my PHP version to PHP 8, it forces to downgrade to version `1.0.9`. And this version doesn't have `afterBuild()` hook, which I rely on.

I tried to force the version to the latest in composer.json file, but it only supports PHP version 7.2. 
```
  Problem 1
    - tightenco/jigsaw v1.3.7 requires illuminate/container ^5.7 -> satisfiable by illuminate/container[v5.7.0, ..., v5.8.36].
    - tightenco/jigsaw[v1.3.0, ..., v1.3.6] require illuminate/container ^5.6 -> satisfiable by illuminate/container[v5.6.0, ..., v5.8.36].
    - illuminate/container[v5.6.0, ..., v5.8.36] require php ^7.1.3 -> your php version (8.0.0) does not satisfy that requirement.
    - tightenco/jigsaw[v1.3.8, ..., v1.3.31] require php ^7.1.3 -> your php version (8.0.0) does not satisfy that requirement.
    - tightenco/jigsaw[v1.3.9, ..., v1.3.13] require erusev/parsedown ^1.8.0@beta -> found erusev/parsedown[1.8.0-beta-1, ..., 1.8.0-beta-7] but it does not match your minimum-stability.
    - tightenco/jigsaw v1.3.32 requires php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires tightenco/jigsaw ^1.3 -> satisfiable by tightenco/jigsaw[v1.3.0, ..., v1.3.32].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```
Please take a look.

**Comment by zaherg** [comment]
you can use `composer update --ignore-platform-reqs` for now and it will work.

**Comment by milon** [comment]
@zaherg thanks, it works. But please try to fix the version number in `composer.json` file whenever you have time.

And thanks again for the wonderful product and support you are giving to the community.

**Comment by zaherg** [comment]
hey @milon  I am not part of the maintainers, but I am sure they are working on upgrading the system to support PHP 8 but it need some time.

Thanks

**Comment by damiani** [comment]
Indeed, we're working on this today!
