### ISSUE TITLE
Unable to persist setContent in afterCollections event listener

### ISSUE THREAD

**Issue by carbontwelve** [tighten/jigsaw#523]
I have been attempting to use [scrivo/highlight.php](https://github.com/scrivo/highlight.php) with my jigsaw projects in order to have code highlighting sans javascript. From this response to issue #357  https://github.com/tighten/jigsaw/issues/357#issuecomment-594012082 I assumed this could be done within the `afterCollections` event by iterating through the posts collection (`$jigsaw->getCollection('posts')`) and using `setContent` on each `CollectionItem` to make my replacement.

I am able to see my replacement working, however it doesn't persist through to the saved html. On delving into the execution path with xdebug I can see that while during the `buildCollections` phase Jigsaw loads and seems to parse the files content, during the `buildSite` phase that parsed content, that I am parsing and replacing with `setContent` gets thrown away - at least with regards to the `MarkdownHandler` as it renders from the file source.

Am I right in assuming that until we have a solution written for #309 that the only way I can get my changes persisted is to switch to listening on the `afterBuild` event and parsing the built files - a far less efficient method, but one I guess will work for now.

**Comment by damiani** [comment]
Yes, `setContent()` alters the content in Jigsaw's internal array (which it uses when referencing a collection item from within another page), but the final parsing of source files for output to `build` uses the original file contents. So, at the moment, using `afterBuild` is the best approach.
