### ISSUE TITLE
Q: Fetch main menu structure from a remote API

### ISSUE THREAD

**Issue by BasJan81** [tighten/jigsaw#525]
Hello there, 👋

Yesterday I used Jigsaw to fetch all my blog posts from a WordPress site through the Rest API. Adding a custom collection -> layout -> fetch -> and there you go. This works, surprisedly easy and good on my local machine. 🤞

Now I would like to do something similar to my primary menu inside the same WordPress CMS. I've already added the menu post type to the Rest API in WordPress, so all content is accessible.

Again, I added a custom collection in config.php  but what should I do with the `'extends' => 'layout'` field? I mean, I don't like to echo/export all menu items as pages inside a _{collection_name} folder. I like to add them to a _partials/nav.blade.PHP template.

Maybe it's not that difficult but this is the first time I'm using Jigsaw I'm still getting used to everything.

Thanks already, for looking at this. I really appreciate it if someone could point me in the direction.

**Comment by BasJan81** [comment]
New day, new motivation. 💪 

I think it's better to create a Helper function inside my config.php file.

Just like this.
```
return [
    'production' => false,
    'baseUrl' => 'https://www.example.com',
    'wpRestAPI' => function( $page, $endPoint ) {
      return json_decode( file_get_contents('http://localhost:8888/cms/wp-vanfoobar/wp-json/wp/v2/'.$endPoint) );
    },
    'collections' => [
...
```

Now I always have my API connection available and I can pass in my own parameter to make any endpoint call.

Just like this.
```
<nav>
  @foreach( $page->wpRestAPI('menus/primary') as $item )
  <a href="{{ $item->url }}">{{ $item->title }}</a>
  @endforeach
</nav>
```


To do:

Make the WordPress API fetching url dynamic. Localhost vs Live site, based on build {production}  🙂

**Comment by damiani** [comment]
You might also consider using a `beforeBuild` event listener, and storing the results of the API call in a config variable (rather than a collection) that you later access from your templates. You'll find some sample code at https://jigsaw.tighten.co/docs/event-listeners/#registering-event-listeners-as-closures that should get you most of the way there!
