### ISSUE TITLE
Generating production build inside build_local

### ISSUE THREAD

**Issue by mostafa-A48** [tighten/jigsaw#526]
This is my webpack configuartion in the below
![image](https://user-images.githubusercontent.com/44500373/103638319-608e5380-4f6a-11eb-9b22-ed1c85b0e63a.png)

when I try npm run production it genrates my complied files isside build_local direcotry and override other files

**Comment by damiani** [comment]
Can you share your `package.json` file? Are you running on Windows?

**Comment by mostafa-A48** [comment]
This is my package.json, Yeah I am on windows
![image](https://user-images.githubusercontent.com/44500373/104349822-0e789f80-5521-11eb-9ef6-a73a1c3b4807.png)

**Comment by mostafa-A48** [comment]
I changed webpack to this 
![image](https://user-images.githubusercontent.com/44500373/104349915-310ab880-5521-11eb-90a9-0316a82ca3b6.png)

and now it works properly

**Comment by mostafa-A48** [comment]
please add a clear way for adding preprocessors in your documentation
