### ISSUE TITLE
Tailwind 2 support?

### ISSUE THREAD

**Issue by RSCipher001** [tighten/jigsaw#528]
By default jigsaw ships with tailwind, is there any plan to change tailwind version to 2? I tried bumping version in `package.json` but build failed.

**Comment by bakerkretzmar** [comment]
Yes, we'll probably update to Tailwind 2 at some point. Feel free to submit a PR to update the default site scaffold!

In the meantime, take a look at Tailwind's [upgrade guide](https://tailwindcss.com/docs/upgrading-to-v2) if you're having issues updating your own site from 1.x to 2.
