### ISSUE TITLE
laravel-mix 6.0, laravel-mix-jigsaw 1.5, Tailwind 2.0

### ISSUE THREAD

**Issue by nathangross** [tighten/jigsaw#532]
Firstly, let me just say that I'm horribly inept with Webpack 😭

I'm really hoping to get set up with Tailwind 2.0. Now, with Laravel Mix 6.0 (Laravel Mix Jigsaw 1.5), I believe this should be doable without Tailwind compatibility mode. 

I'm getting the following error with the default Jigsaw scripts in `package.json`:
```error: unknown option '--hide-modules'```

Simply removing that option from the scripts leads to other issues.

I've looked through the scripts changes that Jeffery makes here:  https://laravel-mix.com/docs/6.0/upgrade but I don't fully grok everything that is changed. 

Is there a set of scripts that will run with this setup? Can someone point me in the right direction?

**Comment by bakerkretzmar** [comment]
Are you starting a new site or working on an existing one? Can you share the other errors you get if you just remove `--hide-modules`? I've seen that error on a bunch of other projects too but usually removing that flag fixes it.

**Comment by nathangross** [comment]
It's new-ish. It's yet to be published. But I started it a few weeks ago prior to the release of laravel-mix-jigsaw 1.5.

Simply removing the `--hide-modules` option, I get the following error:

```
[webpack-cli] Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.optimization.splitChunks.cacheGroups['styles-css/main'] has an unknown property 'type'. These properties are valid:
   object { automaticNameDelimiter?, automaticNameMaxLength?, automaticNamePrefix?, chunks?, enforce?, enforceSizeThreshold?, filename?, maxAsyncRequests?, maxInitialRequests?, maxSize?, minChunks?, minSize?, name?, priority?, reuseExistingChunk?, test? }
 - configuration.output.chunkFilename should be a string.
   -> The filename of non-entry chunks as relative path inside the `output.path` directory.
 - configuration.stats has an unknown property 'preset'. These properties are valid:
   object { all?, assets?, assetsSort?, builtAt?, cached?, cachedAssets?, children?, chunkGroups?, chunkModules?, chunkOrigins?, chunks?, chunksSort?, colors?, context?, depth?, entrypoints?, env?, errorDetails?, errors?, exclude?, excludeAssets?, excludeModules?, hash?, logging?, loggingDebug?, loggingTrace?, maxModules?, moduleAssets?, moduleTrace?, modules?, modulesSort?, nestedModules?, optimizationBailout?, outputPath?, performance?, providedExports?, publicPath?, reasons?, source?, timings?, usedExports?, version?, warnings?, warningsFilter? }
   ```

**Comment by bakerkretzmar** [comment]
Try this (plus any other dependencies you have), and also delete `node_modules` and `package-lock.json` and reinstall everything.

`package.json`:

```js
{
    "private": true,
    "scripts": {
        "dev": "mix",
        "watch": "mix watch",
        "staging": "NODE_ENV=staging mix",
        "prod": "mix --production"
    },
    "devDependencies": {
        "laravel-mix": "^6.0.10",
        "laravel-mix-jigsaw": "^1.5.0",
        "postcss-import": "^14.0.0",
        "tailwindcss": "^2.0.2"
    }
}
```

`webpack.mix.js`

```js
const mix = require('laravel-mix');
require('laravel-mix-jigsaw');

mix.disableSuccessNotifications();
mix.setPublicPath('source/assets/build');

mix.jigsaw()
    .js('source/_assets/js/main.js', 'js')
    .css('source/_assets/css/main.css', 'css', [
        require('postcss-import'),
        require('tailwindcss'),
    ])
    .options({
        processCssUrls: false,
    })
    .version();
```

**Comment by nathangross** [comment]
Ok, this was a bit help, thank you!

I think I had a couple separate issues going on:

I didn't realize I was still on webpack 4. When I tried to update to 5, it was complaining about the version of sass-loader I was using. I'm actually probably not going to use sass on this project, so I just ditched that. Updated to webpack 5 and `npm run watch` was working again. 

I referenced Tailwind's install [guidelines](https://tailwindcss.com/docs/guides/laravel#configure-tailwind-with-laravel-mix) 

But then I had another error: 
`Module not found: Error: Can't resolve 'postcss-loader' in '/Users/nathan/Code/raglestatic'`

So I installed postcss-loader and everything seems to be working as expected. I don't get all the nuance in postcss-loader and postcss-import, but it's working now.

Thanks again. 

```
{
    "private": true,
    "scripts": {
        "dev": "mix",
        "watch": "mix watch",
        "staging": "NODE_ENV=staging mix",
        "prod": "mix --production"
    },
    "devDependencies": {
        "axios": "^0.18.0",
        "cross-env": "^3.2.3",
        "fuse.js": "^3.3.0",
        "highlight.js": "^9.13.1",
        "laravel-mix": "^6.0.10",
        "laravel-mix-jigsaw": "^1.5.0",
        "postcss-import": "^14.0.0",
        "postcss-loader": "^4.1.0",
        "tailwindcss": "^2.0.2",
        "tailwindcss-textshadow": "^2.1.3",
        "vue": "^2.5.21",
        "vue-template-compiler": "^2.5.21",
        "webpack": "^5.16.0"
    }
}
```

```
const mix = require('laravel-mix');
require('laravel-mix-jigsaw');

mix.disableSuccessNotifications();
mix.setPublicPath('source/assets/build');

mix.jigsaw()
    .js('source/_assets/js/main.js', 'js')
    .postCss('source/_assets/css/main.css', 'css', [
        require('tailwindcss'),
    ])
    .version();
```
