### ISSUE TITLE
is it possible to automatically upload to the SFTP server after Jigsaw built is complete?

### ISSUE THREAD

**Issue by itsdanielfelix** [tighten/jigsaw#533]
Hi,

I created my personal site ( https://danielfelix.in/ ) using Jigsaw and I am hosting it on my own VPS.

Usually, I would zip the production build and upload it into my server and unzip it there.

Now my question is 'is it possible to automatically upload to the SFTP server after Jigsaw built is complete?'.

I'm totally new to Jigsaw .. any ideas?

Thanks in advance...

**Comment by damiani** [comment]
You could accomplish this in your Webpack config, by adding the `.then()` directive to `webpack.mix.js` and using something like the https://github.com/pirumpi/sftp-upload#readme package:

```js
mix.js('source/_assets/js/main.js', 'js')
    .sass('source/_assets/sass/main.scss', 'css/main.css')
    .jigsaw()

...

    .then(() => {
        if (process.env.NODE_ENV === 'production') {
            // handle upload here using the SftpUpload library
        }
    });
```

**Comment by bakerkretzmar** [comment]
@damiani beat me to it! You could also use a [listener](https://jigsaw.tighten.co/docs/event-listeners) and run a hook after your build that uploads the site. Flysystem has an SFTP adapter, so if you install `league/flysystem-sftp` you should be able to do something like this (I haven't tested it so you may need to tweak things):

```php
// bootstrap.php
use League\Flysystem\Filesystem;
use League\Flysystem\Sftp\SftpAdapter;

$events->afterBuild(function ($jigsaw) {
    $files = new Filesystem(new SftpAdapter([
        'host' => 'example.com',
        'port' => 22,
        'username' => 'username',
        'password' => 'password',
        'privateKey' => 'path/to/or/contents/of/privatekey',
        'passphrase' => 'passphrase-for-privateKey',
        'root' => '/path/to/root',
        'timeout' => 10,
        'directoryPerm' => 0755,
    ]));

    // Upload the build output
    $files->put($path);
});
```

**Comment by itsdanielfelix** [comment]
@damiani and @bakerkretzmar

thank you guys for your inputs.

will try them and get back with the status.

many thanks...
