### ISSUE TITLE
Problem on run command jigsaw init on Windows

### ISSUE THREAD

**Issue by DasdWaller** [tighten/jigsaw#534]
PHP: v7.3.26
OS: Windows 10

Run command: `php vendor/bin/jigsaw init`

Error:
```
dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../tightenco/jigsaw" && pwd)

if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi

"${dir}/jigsaw" "$@"
```

**Comment by bakerkretzmar** [comment]
l'm not very familiar with Windows but that doesn't look like an error message, it looks like some kind of bash script or shell alias. It's definitely not part of Jigsaw.

Can you double check you don't have shell functions or aliases interfering with running the command, and describe the error in more detail?

**Comment by DasdWaller** [comment]
Sorry its my fault. Just add the `php ...` command and was need to change the slashes to support the windows.
