### ISSUE TITLE
Where best to keep js files in source that don't need compiled—only moved

### ISSUE THREAD

**Issue by nathangross** [tighten/jigsaw#537]
I'm working on a legacy project and has an old javascript slider asset built with jquery (RoyalSlider). Where should I place the `jquery.royalslider.js` file and where should I move it to via mix? My original intent was to keep it in `_assets/js` and use `move.()` to move it but I can't seem to get it configured right.

**Comment by damiani** [comment]
Assuming you have a stock Jigsaw install, I believe `copy` would accomplish this. You can store it in `source/_assets/js`, and use `copy()` to copy it to the `assets/build/js` directory, which then gets copied to your `build_local` or `build_production`:

```
mix.copy('source/_assets/js/jquery.royalslider.js', 'source/assets/build/js')
...
```

If you have multiple similar vendor files, you can do the same with a whole `vendor` directory.

Alternatively, you can add a `vendor` directory to the `assets` directory (the one without the `_` at the beginning), and again, that will automatically get copied. If you do that, you don't need to add any `copy()` step to your `webpack.mix.js` file.

**Comment by nathangross** [comment]
Ok, that was it. I wasn't prepending `source/assets/build/`. 🤦🏻‍♂️
