### ISSUE TITLE
Command for Netlify deployment doesn't work

### ISSUE THREAD

**Issue by vandershraaf** [tighten/jigsaw#539]
Hi team,

I'm very new to Jigsaw. I followed the instruction given for Netlify deployment to use the following command in netlify.toml : 

`command = "npm run production"`

However, the build failed. So I modified it to use the following instead, which works well: 

`command = "./vendor/bin/jigsaw build production && npm run production"`

Which command is supposed to me documented? My understanding is the jigsaw build should generate the site's files, and then npm run should process the assets. Reference : [https://github.com/tighten/jigsaw/issues/283](https://github.com/tighten/jigsaw/issues/283)

Note : 
- My latest project uses the blog starter template, so I had to use `npm run prod` instead of `npm run production`.

Thanks,
Ashraf

**Comment by bakerkretzmar** [comment]
Can you share the failed built output? What error messages did you see? `vendor/bin/jigsaw build` just builds the site's content, `npm run prod` compiles the assets _and_ runs `vendor/bin/jigsaw build`.

**Comment by vandershraaf** [comment]
The output from Netlify:

`9:56:49 PM: ────────────────────────────────────────────────────────────────
9:56:49 PM:   1. build.command from netlify.toml                            
9:56:49 PM: ────────────────────────────────────────────────────────────────
9:56:49 PM: ​
9:56:49 PM: $ npm run production
9:56:49 PM: npm ERR! missing script: production
9:56:49 PM: npm ERR! A complete log of this run can be found in:
9:56:49 PM: npm ERR!     /opt/buildhome/.npm/_logs/2021-02-03T13_56_49_376Z-debug.log
9:56:49 PM: ​
9:56:49 PM: ────────────────────────────────────────────────────────────────
9:56:49 PM:   "build.command" failed                                        
9:56:49 PM: ────────────────────────────────────────────────────────────────
9:56:49 PM: ​
9:56:49 PM:   Error message
9:56:49 PM:   Command failed with exit code 1: npm run production
`
I used the blog starter template, which uses 'npm run prod' instead of 'npm run production' (based on package.json from https://github.com/tighten/jigsaw-blog-template) so it probably makes sense that the command is invalid. 

Afterward I included the jigsaw build command, and the build worked. 

If I leave it to 'npm run prod' or 'npm run production', it should still work fine? I can try this out once I got chance.

**Comment by bakerkretzmar** [comment]
Yeah `npm run prod` should work, try that.
