### ISSUE TITLE
Is there a way to tidy up the rendered HTML?

### ISSUE THREAD

**Issue by austincarpenter** [tighten/jigsaw#542]
I know the indentation of rendered HTML isn't a real issue, but it would be nice to have a way to tidy it up a little. I looked into `html-webpack-plugin` and `beautify-html-webpack-plugin` using `.webpackConfig({ ... ])` but ran into some errors as I'm not too familiar with Webpack/Mix... Is anyone using something like this to pretty things up and could lend a hand?

**Comment by bakerkretzmar** [comment]
I'd suggest using a Jigsaw [listener](https://jigsaw.tighten.co/docs/event-listeners/) to do this in PHP after the site is built. Check out the listeners in the [blog](https://github.com/tighten/jigsaw-blog-template/tree/main/listeners) and [docs](https://github.com/tighten/jigsaw-docs-template/tree/main/listeners) templates as examples.
