### ISSUE TITLE
Home/index page always stays selected when using helper function from docs

### ISSUE THREAD

**Issue by DarpanKulkarni** [tighten/jigsaw#551]
I am trying to change color of the menu item for current page, I am using helper function from the documentation but when I open any other page than home/index page the index/home page stays selected.

config.php
```
return[
    ...

    'selected' => function ($page, $section) {
        return $page->getPath() == $section || str_contains($page->getPath(), $section) ? 'text-red' : '';
    }
]
```

main.blade.php
```
<nav>
    <a href="{{ $page->baseUrl }}/" class="{{ $page->selected('') }}">Home</a>
    <a href="{{ $page->baseUrl }}/about" class="{{ $page->selected('about') }}">About</a>
    <a href="{{ $page->baseUrl }}/contact" class="{{ $page->selected('contact') }}">Contact</a>
</nav>
```

Screenshots:

![image](https://user-images.githubusercontent.com/66897147/113544701-6e558280-9606-11eb-99de-87d111410713.png)
![image](https://user-images.githubusercontent.com/66897147/113544732-7e6d6200-9606-11eb-84e5-ec3570cf014e.png)
![image](https://user-images.githubusercontent.com/66897147/113544759-89c08d80-9606-11eb-8843-8eae39547dd4.png)

**Comment by damiani** [comment]
This is working correctly in my tests; can you send me a link to your code repo so I can take a closer look?

![selected](https://user-images.githubusercontent.com/357312/113574638-ca2b0600-961c-11eb-9bf0-6124ec88b104.jpg)

**Comment by DarpanKulkarni** [comment]
It is working on my another site with older jigsaw version but not on new one.

Here is repo: https://github.com/DarpanKulkarni/jigsaw-test

**Comment by damiani** [comment]
The example in the Jigsaw documentation uses Laravel's `Str` class for `Str::contains`, but your example uses the PHP 8.0 method `str_contains` ... unfortunately, the two have slightly different behavior:

```php
Str::contains('/about', ''); // returns false

str_contains('/about', ''); // returns true
```

If you switch to using `Str::contains` (add `use Illuminate\Support\Str;` to the top of your config file), your code should work as expected.
