### ISSUE TITLE
Adding a feature to filter by multiple tags...

### ISSUE THREAD

**Issue by TCRodriguez** [tighten/jigsaw#552]
Hello!

I hope this is the right place and way to ask this question. I'm a newer developer and am learning about static site generators as I build out a blog to my personal site using jigsaw. I've been working on a `tags` feature where you can filter the "index" page of all posts by either one or more tags. (As in, give me all the posts that have the following: #laravel, #javascript, #css, etc.)

Is this possible to do within the context of a static site generator? Or is this a limitation of using an SSG and would need a database for this functionality to work?  I've gotten as far as figuring out how to add the tags to a pot in the YAML front matter, and then displaying those tags in each post. 

Thank you for the time in advance!

**Comment by bakerkretzmar** [comment]
Hi! Short answer: yes, this is possible with Jigsaw. Basically, you have to determine what all your tags are in advance and then generate static pages for every tag.

Long answer: our [blog template](https://github.com/tighten/jigsaw-blog-template) actually includes an example of how to do this—take a look at the `categories` collection and the `source/_layouts/category.blade.php` view. The magic happens in the `posts` method of the `categories` collection:

```php
        'categories' => [
            'path' => '/blog/categories/{filename}',
            'posts' => function ($page, $allPosts) {
                return $allPosts->filter(function ($post) use ($page) {
                    return $post->categories ? in_array($page->getFilename(), $post->categories, true) : false;
                });
            },
        ],
```

There's an entry for each category in the `source/_categories` directory, and every time a category page is rendered, the `category.blade.php` layout calls the function above to determine which posts belong to that category. The function gets the category page itself as the first argument, and then **the entire `posts` collection** is passed in from the view as its second argument, which it filters to find posts matching the current category.

This way of doing it requires you to know every category/tag in advance, which is probably fine. But if you have tons, or you don't want to create a file for each one, you could also generate the collection of tags dynamically. This is a bit more complicated, and involves setting up a listener to wait until your collections have been built and then generate and add a new `tags` collection based on all of your posts' tags. Take a look at #273 and https://gist.github.com/nikazooz/6cce7944dbef8db376bd73ed240220bd for discussion and examples of how to set this up.

Finally, I'm not sure if this is what you meant exactly, but if you need to be able to filter by multiple tags at the same time that should technically be possible. Every 'filter' state still needs its own page, so you'd basically be looking at the second option above but dynamically generating collection items for every tag _and every possible combination of tags_. Depending on how many tags you have, that could get pretty messy pretty fast, so if that's something you need you may want to look into a more flexible search setup—the blog template also has [an example of setting up search](https://github.com/tighten/jigsaw-blog-template/blob/main/source/_assets/js/components/Search.vue) with Fuse.js.

Closing this but feel free to reply if you have other questions!

**Comment by palexandrite** [comment]
@bakerkretzmar thank you for this good solution. But If there a pagination it will break.

**Comment by intrepidws** [comment]
@palexandrite Were you ever able to get this working with pagination?
