### ISSUE TITLE
Custom ordering collections

### ISSUE THREAD

**Issue by zawilliams** [tighten/jigsaw#553]
Is there a simple way of custom ordering collections built-in that is perhaps not documented?

For example, if I have a collections folder with the following:

```
_features/
    my-feature.blade.php
    another-feature.blade.php
    new-feature.blade.php
```

I was trying to order them by prepending a number at the beginning of the filename (e.g. `1-my-feature.blade.php`) but then the slug has the number in it.

Any ideas or undocumented info about sorting this way?

**Comment by bakerkretzmar** [comment]
Not sure I'm understanding correctly, but if you want collection items in a completely custom order there are basically two ways to do that:

**Option 1**: With custom filenames, which is the example you showed above. If you want to do that and _not_ have the number in the slug, you can configure the collection's `path` to override this and then specify a `slug` in each entry's front matter:

**`config.php`**
```php
<?php

return [
    'collections' => [
        'features' => [
            'path' => 'slug',
        ],
    ],
];
```

**`_features/1-my-feature.blade.php`**
```markdown
---
slug: my-feature
---
# My Feature
```

**Option 2**: With a custom sort key in the frontmatter:

**`config.php`**
```php
<?php

return [
    'collections' => [
        'features' => [
            'sort' => 'order',
        ],
    ],
];
```

**`_features/my-feature.blade.php`**
```markdown
---
order: 1
---
# My Feature
```

Does that help?

**Comment by zawilliams** [comment]
@bakerkretzmar that helps, yes. Just wanted to make sure I wasn't missing some special/automatic way of doing this, like prepending a filename with `-1` (e.g. `-1-filename.blade.php`) or something. Thanks!
