### ISSUE TITLE
Passing front-matter to custom directive bug?

### ISSUE THREAD

**Issue by imaje89** [tighten/jigsaw#554]
Hi All 👋 

I have a strange issue when passing variables to a custom image-handling directive.
Right now I have something like the following

```
Blog post front-matter

imageUrl: /path/to/image.png


Directive in blade template blog post layout

@image({
"path": "{{$page->imageUrl}}"
})

Custom Directive  (Simplified)

 return [
  'image' => function ($param) {
        $params = json_decode($param, true);
        $image = isset($params["path"]) ? $params["path"] : "";
        $explodedImage = explode('.', $image);
        
        $render = <<<EOD
          <picture>
            <source srcset="/assets/images/$explodedImage[0].webp" type="image/webp">
            <img src="/assets/images/$explodedImage[0].$explodedImage[1]" />
          </picture>
        EOD;
```

The key bit here is the `explode('.', $image)` where I want to be able to split the path from it's file extension so I can render generate the path to the WebP version and non-webp version in the next few lines. 

In this case, when I am passing an image path manually, like this..

```
@image({
"path": "/path/to/image.png"
})
```

**there are no issues** but when I try to inject a value, in this case from a posts front-matter (or any variable it seems) like so..

```
@image({
"path": "{{$pathToImage}}"
})
```

Then something seems to go wrong.. 
When I output the value of `$render` to console, I get the following

```
          <picture>
            <source srcset="/assets/images/{{$pathToImage}}.webp" type="image/webp">
            <img src="/assets/images/{{$pathToImage}}" />
          </picture>
```

The input doesn't seem to have injected the variables value into the directive and instead just the variable reference.
The actual output in the HTML I am getting is like so.. 

```
          <picture>
            <source srcset="/assets/images/path/to/image.png.webp" type="image/webp">
            <img src="/assets/images/image.png" />
          </picture>
```

I am not sure what's going on here or if I am misunderstanding a fundamental behaviour of Jigsaw.
Any help is greatly appreciated.

**Comment by damiani** [comment]
I believe that is standard behavior for custom directives in Blade, that the parameters are not parsed with Blade before being passed to the directive. Instead of passing an arbitrary JSON object, could you instead update your directive so it accepts:

```php
// either 
@image('/path/to/image.png')

// or
@image($pathToImage)
```

**Comment by imaje89** [comment]
Thanks @damiani I think my fundamental understanding of custom directives need a change. Reading around and this post is particularly helpful

https://techsemicolon.github.io/blog/2019/01/10/laravel-improving-readility-with-blade-directives/

I will have to rewrite it.

**Comment by bakerkretzmar** [comment]
@imaje89 I think you may be able to get this working with a couple smaller changes—arguments to directives should be interpreted as PHP code, so if you pass an actual PHP array instead of a JSON object I think what you have should work. Try this:

```php
// blog-template.blade.php

@image(['path' => $page->imageUrl])
```

```php
// image directive

return [
    'image' => function (array $params) {
        $image = $params['path'] ?? '';
        $explodedImage = explode('.', $image);

        return <<<HTML
            <picture>
                <source srcset="/assets/images/{$explodedImage[0]}.webp" type="image/webp">
                <img src="/assets/images/{$explodedImage[0]}.{$explodedImage[1]}" />
            </picture>
        HTML;
    },
];
```
