### ISSUE TITLE
Inline stylesheet gives asset path is not valid error

### ISSUE THREAD

**Issue by imaje89** [tighten/jigsaw#561]
Hi all, me again.. 

I have an odd issue whereby if I use mix in the usual way to get a stylesheet URL, all is well e.g.

`<link rel="stylesheet" as=“style” href="{{ mix('/styles/priority.css', 'assets') }}">`

Whereas if I want to inline this using `{{ inline(mix(...)) }}` the site is not build with the following error in the console

`Given asset path is not valid: /assets/styles/priority.css?id=2b5d50028ff9afabaaea`

Here's my usage...

```
<style>
{{ inline(mix('styles/priority.css', 'assets')) }}
</style>
```

I can see the file `priority.css` in my assets folder in both my `/source` directory and also in the correct build directory.

Here's a snippet from my `webpack.mix.js` file which deals with the separate css files..

```
    mix.setPublicPath('source/assets/');
    mix.disableSuccessNotifications();
    mix.jigsaw({
            watch: ['config.php', 'source/**/*.md', 'source/**/*.php', 'source/_assets/**/*.scss', 'source/_data/*.json', 'source/_assets/**/*.js'],
        })
        .sass('source/_assets/sass/main.scss', 'styles/main.css')
        .sass('source/_assets/sass/priority.scss', 'styles/priority.css')
        .options({
            processCssUrls: false
        })
        .version();
```

I've managed to find a work-around for this locally by instead relying on php to retrieve the files contents by doing this..

`
@php 
   include public_path('assets/styles/priority.css')
@endphp 
`
but it is too brittle for serious use.. 

Any help is greatly appreciated! :)

**Comment by bakerkretzmar** [comment]
Try removing `.version()` from your Mix build, it looks like it's looking for a file path including the `?id=2b...` query string, which is only in the Mix manifest and not part of the actual filename.

**Comment by imaje89** [comment]
Thank you @bakerkretzmar  for your suggestion, unfortunately it doesn't look like it helps :( Keep in mind that when I use 

```
<link rel="stylesheet" as="style" href="{{ mix('styles/priority.css') }}">
<link rel="stylesheet" as="style" href="{{ mix('/styles/main.css') }}">
```

It builds fine and each file URL is correct including the cache-breaker Query string value

**Comment by bakerkretzmar** [comment]
Okay, looks like our `inline()` helper requires that your asset path start with `/assets/build/css` or `/assets/build/js`.

So you'll want to make a few path changes:

```diff
- mix.setPublicPath('source/assets/');
+ mix.setPublicPath('source/assets/build');
```

```diff
- .sass('source/_assets/sass/main.scss', 'styles/main.css')
- .sass('source/_assets/sass/priority.scss', 'styles/priority.css')
+ .sass('source/_assets/sass/main.scss', 'css')
+ .sass('source/_assets/sass/priority.scss', 'css')
```

```diff
- {{ inline(mix('styles/priority.css', 'assets')) }}
+ {{ inline(mix('css/priority.css', 'assets/build')) }}
```

This definitely isn't a great constraint to have and we'll look into removing it, but since that would be a big breaking change it likely won't happen soon unfortunately.

**Comment by imaje89** [comment]
Ah okay, I will try this out. Thank you for looking into it, I agree it's not an ideal constraint and I will be keen see a fix in a future version :)
