### ISSUE TITLE
Folder for routing

### ISSUE THREAD

**Issue by SelfMade2001** [tighten/jigsaw#562]
Is there a way to have all the routes in one file? I searched a lot and could not find any way to achieve this. It would be a nice feature to add or if there is a way to do it, then please add it to the jigsaw documentation.

To make the issue clear: 
My folder structure at the moment looks like this:
---source
***|--- _assets
***|--- _firstRoute
*********|--- index.blade.php
***|--- _layouts
***|--- _secondRoute
*********|--- index.blade.php
***|--- _thirdRoute
*********|--- index.blade.php
***|--- assets
***|--- index.blade.php

And for large projects it would be nice to look somewhat like this:
---source
***|--- _assets
***|--- _layouts
***|--- _views
*********|--- _firstRoute
***************|--- index.blade.php
*********|--- _secondRoute
***************|--- index.blade.php
*********|--- _thirdRoute
***************|--- index.blade.php
***|--- assets
***|--- index.blade.php

Is this possible? Because at the moment, this folder _view breaks jigsaw, so it will not find any route

**Comment by bakerkretzmar** [comment]
@SelfMade2001 did you manage this get this working?

**Comment by lukebouch** [comment]
@SelfMade2001 If you are still having trouble, let me know. I'm happy to help!
