### ISSUE TITLE
blog template error running npm run prod

### ISSUE THREAD

**Issue by jvallef** [tighten/jigsaw#589]
% npm run prod

> prod
> mix --production

✖ Mix
  Compiled with some errors in 8.14s

● Mix █████████████████████████ done (99%) plugins 
 BrowserSyncPlugin

ERROR in ./source/_assets/sass/main.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(6:4) /Users/jos/Web/jigsaw/source/_assets/sass/_base.scss The `.font-semibold` class does not exist, but `font-semibold` does. If you're sure that `.font-semibold` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

  4 | 
  5 | a {
> 6 |     @apply .font-semibold;
    |    ^
  7 |     @apply .no-underline;
  8 |     @apply .text-blue-600;

    at processResult (/Users/jos/Web/jigsaw/node_modules/webpack/lib/NormalModule.js:751:19)
    at /Users/jos/Web/jigsaw/node_modules/webpack/lib/NormalModule.js:853:5
    at /Users/jos/Web/jigsaw/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/jos/Web/jigsaw/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/jos/Web/jigsaw/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/Users/jose/Web/jigsaw/node_modules/postcss-loader/dist/index.js:140:7)

**Comment by isAdamBailey** [comment]
The error is telling you the answer, have you tried removing the `.` from the class in your `@apply`?

**Comment by bakerkretzmar** [comment]
@jvallef feel free to comment again if removing the leading `.` from your class names doesn't resolve this.
