### ISSUE TITLE
Laravel 8.* not supported

### ISSUE THREAD

**Issue by jinrenjie** [tighten/jigsaw#597]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - tightenco/jigsaw[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6] require illuminate/container ^5.6 -> found illuminate/container[v5.6.0, v5.6.1, v5.6.2, v5.6.3, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, 5.6.x-dev, v5.7.0, v5.7.1, v5.7.2, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.7.10, v5.7.11, v5.7.15, 5.7.17, 5.7.18, 5.7.19, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, 5.7.x-dev, v5.8.0, v5.8.2, v5.8.3, v5.8.4, v5.8.8, v5.8.9, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - tightenco/jigsaw v1.3.7 requires illuminate/container ^5.7 -> found illuminate/container[v5.7.0, v5.7.1, v5.7.2, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.7.10, v5.7.11, v5.7.15, 5.7.17, 5.7.18, 5.7.19, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, 5.7.x-dev, v5.8.0, v5.8.2, v5.8.3, v5.8.4, v5.8.8, v5.8.9, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - tightenco/jigsaw[v1.3.8, v1.3.9, v1.3.10, v1.3.11, v1.3.12, v1.3.13, v1.3.14, v1.3.15] require illuminate/container ^5.8 -> found illuminate/container[v5.8.0, v5.8.2, v5.8.3, v5.8.4, v5.8.8, v5.8.9, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - tightenco/jigsaw[v1.3.16, v1.3.17, v1.3.18, v1.3.19, v1.3.20, v1.3.21, v1.3.22, v1.3.23, v1.3.24, v1.3.25, v1.3.26, v1.3.27, v1.3.28, v1.3.29, v1.3.30, v1.3.31] require php ^7.1.3 -> your php version (8.0.10) does not satisfy that requirement.
    - tightenco/jigsaw v1.3.32 requires php ^7.2 -> your php version (8.0.10) does not satisfy that requirement.
    - tightenco/jigsaw[v1.3.33, v1.3.34, v1.3.35, v1.3.36, v1.3.37, v1.3.38] require illuminate/container ^7.0 -> found illuminate/container[v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.2.0, v7.2.1, v7.2.2, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.26.1, v7.27.0, v7.28.0, v7.28.1, v7.28.2, v7.28.3, v7.28.4, v7.29.0, v7.29.1, v7.29.2, v7.29.3, v7.30.0, v7.30.1, v7.30.2, v7.30.3, v7.30.4, v7.30.5, 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires tightenco/jigsaw ^1.3 -> satisfiable by tightenco/jigsaw[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.10, v1.3.11, v1.3.12, v1.3.13, v1.3.14, v1.3.15, v1.3.16, v1.3.17, v1.3.18, v1.3.19, v1.3.20, v1.3.21, v1.3.22, v1.3.23, v1.3.24, v1.3.25, v1.3.26, v1.3.27, v1.3.28, v1.3.29, v1.3.30, v1.3.31, v1.3.32, v1.3.33, v1.3.34, v1.3.35, v1.3.36, v1.3.37, v1.3.38].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require tightenco/jigsaw:*" to figure out if any version is installable, or "composer require tightenco/jigsaw:^2.1" if you know which you need.

**Comment by bakerkretzmar** [comment]
Correct, Jigsaw depends on version `7.x` of the `illuminate/*` components, `8.x` is not supported.

It's not clear from that error message which package you're trying to install or which version of Jigsaw you're using, if you have specific questions feel free to comment below!
