### ISSUE TITLE
PHP 8.1 and Laravel 8 support

### ISSUE THREAD

**Issue by zaherg** [tighten/jigsaw#601]
I have tried to collect all the info that I can:

running `npm run dev` on a device with PHP 8.1 will produce the following error:

```
webpack compiled successfully

Deprecated: Return type of Illuminate\Container\Container::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/container/Container.php on line 1270

Deprecated: Return type of Illuminate\Container\Container::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/container/Container.php on line 1281

Deprecated: Return type of Illuminate\Container\Container::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/container/Container.php on line 1293

Deprecated: Return type of Illuminate\Container\Container::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/container/Container.php on line 1306

Deprecated: Return type of Illuminate\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/support/Collection.php on line 1349

Deprecated: Return type of Illuminate\Support\Collection::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/support/Collection.php on line 1360

Deprecated: Return type of Illuminate\Support\Collection::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/support/Collection.php on line 1372

Deprecated: Return type of Illuminate\Support\Collection::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/support/Collection.php on line 1387

Deprecated: Return type of Illuminate\Support\Collection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/support/Collection.php on line 1304

Deprecated: Return type of Illuminate\Support\Collection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/support/Collection.php on line 1294

Deprecated: Return type of Illuminate\Support\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/support/Traits/EnumeratesValues.php on line 768

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /Users/zaher/Sites/workspace/xxx/vendor/tightenco/jigsaw/src/Console/BuildCommand.php on line 101

Deprecated: Return type of Illuminate\View\View::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/view/View.php on line 309

Deprecated: Return type of Illuminate\View\View::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/view/View.php on line 320

Deprecated: Return type of Illuminate\View\View::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/view/View.php on line 332

Deprecated: Return type of Illuminate\View\View::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/view/View.php on line 343
```

This is a fresh site with blog template, hope this helps

**Comment by jimleeder123** [comment]
This is happening for me too even after updating everything via both composer and NPM. Looks like Laravel pacakages though? 

I am getting the same errors as pasted.

**Comment by saleem-hadad** [comment]
I was having the same thing, try this:
```
composer update --ignore-platform-reqs
```

**Comment by jimleeder123** [comment]
Has there been any updates on this, please?

**Comment by zaherg** [comment]
> I was having the same thing, try this:
> 
> ```
> composer update --ignore-platform-reqs
> ```

This won't solve the problem, this will only ignore the platform requirements, so the problem will still exists.
one way to solve the problem is waiting for the result of the upgrade https://github.com/tighten/jigsaw/issues/601#issuecomment-986841081

**Comment by Ifriqiya** [comment]
I currently have this issue on 2 projects after updating to xampp to get php 8.1.1. But another set of 2 projects works fine. I'm at a complete loss as to why there're no errors/issues on one set when they have near identical package requirements.

**Comment by bakerkretzmar** [comment]
Jigsaw v1.3.40 now uses `illuminate/*` 8.

**Comment by jimleeder123** [comment]
This now works on PHP 8.1 - thanks

**Comment by mreduar** [comment]
The error 
`Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in \vendor\tightenco\jigsaw\src\Console\BuildCommand.php on line 103`
is still presented. I am using PHP 8.1.2

**Comment by SilvaQ** [comment]
is still presented. I am using PHP 8.1.3

**Comment by bakerkretzmar** [comment]
@SilvaQ what's your exact error and what version of Jigsaw are you running? Feel free to open a PR to fix any deprecation errors, you can take a look at #608 to see how I was handling it.

**Comment by SilvaQ** [comment]
@bakerkretzmar 
The same question that was asked at the beginning of this discussion。

However, the problem was not solved when I updated composer, so I deleted everything under ~/. Composer and updated it again， after the installation, the problem disappeared..

If you have a problem with composer global update, You might want to try deleting things under ~/. Composer and re-update globally to see if the problem goes away。

@bakerkretzmar I have no more questions now, thank you

**Comment by RushiNCode93** [comment]
> I have tried to collect all the info that I can:
> 
> running `npm run dev` on a device with PHP 8.1 will produce the following error:
> 
> ```
> webpack compiled successfully
> 
> Deprecated: Return type of Illuminate\Container\Container::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/container/Container.php on line 1270
> 
> Deprecated: Return type of Illuminate\Container\Container::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/container/Container.php on line 1281
> 
> Deprecated: Return type of Illuminate\Container\Container::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/container/Container.php on line 1293
> 
> Deprecated: Return type of Illuminate\Container\Container::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/container/Container.php on line 1306
> 
> Deprecated: Return type of Illuminate\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/support/Collection.php on line 1349
> 
> Deprecated: Return type of Illuminate\Support\Collection::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/support/Collection.php on line 1360
> 
> Deprecated: Return type of Illuminate\Support\Collection::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/support/Collection.php on line 1372
> 
> Deprecated: Return type of Illuminate\Support\Collection::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/support/Collection.php on line 1387
> 
> Deprecated: Return type of Illuminate\Support\Collection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/support/Collection.php on line 1304
> 
> Deprecated: Return type of Illuminate\Support\Collection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/support/Collection.php on line 1294
> 
> Deprecated: Return type of Illuminate\Support\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/support/Traits/EnumeratesValues.php on line 768
> 
> Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /Users/zaher/Sites/workspace/xxx/vendor/tightenco/jigsaw/src/Console/BuildCommand.php on line 101
> 
> Deprecated: Return type of Illuminate\View\View::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/view/View.php on line 309
> 
> Deprecated: Return type of Illuminate\View\View::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/view/View.php on line 320
> 
> Deprecated: Return type of Illuminate\View\View::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/view/View.php on line 332
> 
> Deprecated: Return type of Illuminate\View\View::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zaher/Sites/workspace/xxx/vendor/illuminate/view/View.php on line 343
> ```
> 
> This is a fresh site with blog template, hope this helps

I got the same error, but
I'm trying to upgrade only the PHP version for my Laravel project,

**My Laravel Framework version is 6.20.19 and my PHP version is 7.4,**

now I want to upgrade **only php version php 7.4 to PHP 8.1** for my current Laravel project, how can I do without upgrading the Laravel version?

I have configured PHP 8.1 in my Linux System and configured my Laravel 6.20 version project, and made some changes in composer.json.

"require": {
        "php": "^8.1",

and Now run the project, and get above same a bunch of errors.

Does any one have a solution for this? please guide me on this.
