### ISSUE TITLE
Upgrade to Tailwind 3 creates infinite loop in 'npm run watch'

### ISSUE THREAD

**Issue by adrelliott** [tighten/jigsaw#607]
Bit of a strange one - when I try to upgrade tailwind to 3.0, then run `npm run watch` the terminal window shows infinite rebuilding, and there is a 'cache' directory that appears and disappears in the root.

I tried it on the vanilla jigsaw build and the blog template, and it happened on both.

(On a MBP and not using anything like docker - if that helps)

I have a screen recording of this if it's any use.

**Comment by adrelliott** [comment]
Fantastic! Thanks!

**Comment by horuskol** [comment]
Unfortunately for me, the solution at https://github.com/laravel-mix/laravel-mix/issues/1942#issuecomment-998148038 was only part of it.

I'm generating some intermediate markdown files into a temporary folder under source - and this was causing the Tailwind CSS JIT to loop, even with the above fix. Luckily, it wasn't too hard to adapt - the temporary files don't use any CSS utilities that don't already exists elsewhere:

```// tailwind.config.js

module.exports = {
  content: require('fast-glob').sync([
    'source/**/*.{blade.php,md,html,vue}',
    '!source/**/_tmp/*' // exclude temporary files
  ],{ dot: true }),
```

**Comment by aboustayyef** [comment]
I've been having this problem with all my Jigsaw projects, and the solutions suggested here did not work for me... I did some further digging online and I read It has to do with the locations of the images and fonts (but I don't use fonts so images in my case). My problem is that I don't even know how to troubleshoot this...

**Comment by lukebouch** [comment]
@aboustayyef I have run into a similar issue in the past and I can't recall what I did to fix it. Are you able to let me see your repository and I will try to diagnose it?

**Comment by lukebouch** [comment]
@aboustayyef Try this: https://github.com/adrelliott/oblongloves/commit/aa70e63f2cb16b042b31b813988087f45a27e089

It worked for me. Don't forget to `npm install fast-glob`.

**Comment by aboustayyef** [comment]
Thanks @lukebouch... What I did is read [this explanation](https://tailwindcss.com/docs/content-configuration#styles-rebuild-in-an-infinite-loop) in the Tailwind docs of why the issue takes place... 
I remember trying the fast-glob fix but it didn't work, so I ended up choosing more specific files in the config instead... But maybe I should give fast-glob another try...

**Comment by lukebouch** [comment]
@aboustayyef awesome! I would give fast-glob another try.

**Comment by adrelliott** [comment]
I write a mini-post about this in the discussion tab

Hope it's useful. 

https://github.com/tighten/jigsaw/discussions/616

**Comment by aboustayyef** [comment]
Thanks. Good reference for the future 👍🏻

**Comment by walirazzaq** [comment]
For anyone who is still facing this issue with remote collections and doing all the above updates and trying solutions.
you can try this in `webpack.mix.js`
```JS
//--- Tested and working for me.
mix.jigsaw({
 watch:{
    noDirs:[
        ''source/_assets/'', 
        'source/assets/',
        'source/_remote_collection_name', // Explicitly list dirs for remote collections
    ]
   }
})

//----OR, maybe----
// Not tested, may work, not sure about negated pattern 😵‍💫
mix.jigsaw({
 watch:{
    dirs:['source/*/', '!source/**/_tmp']
   }
})
```

**Comment by Grasshopperclement32** [comment]
> Unfortunately for me, the solution at [laravel-mix/laravel-mix#1942 (comment)](https://github.com/laravel-mix/laravel-mix/issues/1942#issuecomment-998148038) was only part of it.
> 
> I'm generating some intermediate markdown files into a temporary folder under source - and this was causing the Tailwind CSS JIT to loop, even with the above fix. Luckily, it wasn't too hard to adapt - the temporary files don't use any CSS utilities that don't already exists elsewhere:
> 
> ```
> 
> module.exports = {
>   content: require('fast-glob').sync([
>     'source/**/*.{blade.php,md,html,vue}',
>     '!source/**/_tmp/*' // exclude temporary files
>   ],{ dot: true }),
> ```





https://inline-styles25.github.io/ZqzjMQCKfuChritnQ3WavLrCtolcBedpkLvZd4jqig/
