### ISSUE TITLE
Update stub

### ISSUE THREAD

**Issue by cdarken** [tighten/jigsaw#611]
Hello, I hit some issues with my fresh project when I tried to use `mix.styles`, I kept getting this error: `Unable to locate Mix file: /css/main.css'`.
After trying the `blog` template it worked, and after some hair pulling I noticed that the `package.json` from the `blog` template was using `laravel-mix-jigsaw` version 2.0.0 while the simple stub container in this repo is still using 1.5.0.
I think that should be updated too, maybe other packages too if it's the case.

**Comment by lukebouch** [comment]
I ran into a similar issue a little while back.
