### ISSUE TITLE
html files not kept as is on build

### ISSUE THREAD

**Issue by jk-keller** [tighten/jigsaw#631]
If I'm reading [the docs](https://jigsaw.tighten.com/docs/content-other-file-types/) correctly, `.html` files shouldn't be modified by jigsaw, but behavior I am experiencing is they get changed to folder named `{filename}` and an `index.html` built. 

![Screen Shot 2022-05-11 at 16 35 52](https://user-images.githubusercontent.com/25354950/168125305-8a925200-10b7-453f-ae12-9b4dcfbfac01.png)

Easy enough to rename files as `.blade.php` and add `permalink:` front matter, but doc is confusing.

**Comment by bakerkretzmar** [comment]
Oh I see what you mean, it's doing that to plain `.html` files too. Hmm.

**Comment by bakerkretzmar** [comment]
What's in that `goodbye.html` file? Does it have YAML frontmatter?

**Comment by jk-keller** [comment]
No YAML frontmatter. It's just a static html file. I noticed the behavior when I put a google site verification file (which of course isn't really an html file) in my source folder and it was getting turned into a folder & index file.

**Comment by bakerkretzmar** [comment]
You can change the file extension to `.blade.html` and add frontmatter to manually set a permalink:

```mdx
---
permalink: google-site-verification.html
---
<!-- contents -->
```

See https://github.com/tighten/jigsaw/issues/629#issuecomment-1235547721.
