### ISSUE TITLE
Browsersync does not appear to be working by default

### ISSUE THREAD

**Issue by piercemcgeough** [tighten/jigsaw#655]
**Steps to reproduce**

1. `mkdir my-project`
2. `cd my-project`
3. `composer require tightenco/jigsaw`
4. `vendor/bin/jigsaw init`
5. `npm install`
6. `npm run watch`

If I were to init the docs or blog it would bring in browsersync ok. 

I can manually add browsersync to the regular jigsaw and it will work ok. 

I was looking but can't find where i would make the required changes to the repo as a PR.

**Comment by bakerkretzmar** [comment]
Browsersync isn't included in the default site, it's intentionally kept really simple. If you want to use it you have to install it and set it up yourself (as you did).
