### ISSUE TITLE
Unknown error being thrown after webpack compiling successfully

### ISSUE THREAD

**Issue by pTinosq** [tighten/jigsaw#673]
Been stuck on this one for two days now. Every time I run `npm run dev` or `npm run prod` I get the following error:

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn vendor\bin\jigsaw ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn vendor\\bin\\jigsaw',
  path: 'vendor\\bin\\jigsaw',
  spawnargs: [ 'build', 'production' ]
}

Node.js v18.12.1
```
The webpack compiles successfully and when I run `vendor\bin\jigsaw build` I get no errors at all.

No useful information from the error as far as I can see, I've googled and every time they tell me to delete node_modules. I've reinstall node, deleted the node_modules folder more times than I can count and cleared my npm cache. Still no luck 🤔

If anyone happens to know what could be causing this, please let me know.

**Comment by husseinalhammad** [comment]
I ran into this when using the latest version of `laravel-mix-jigsaw` with an older version of Jigsaw. What worked for me is rolling back to an older version of `laravel-mix-jigsaw` ([v2.0.0](https://github.com/tighten/laravel-mix-jigsaw/releases/tag/v2.0.0)).

It may help the maintainers if you share the PHP, Jigsaw and `laravel-mix-jigsaw` versions you're using.

**Comment by pTinosq** [comment]
I'm using jigsaw 1.6 and laravel-mix-jigsaw 2.0.0

Don't really have any php code other than my blade.php files of which there are so many I don't even know how I would share them

**Comment by pTinosq** [comment]
Updating to laravel-mix-jigsaw 2.1.0 fixed this error.

This PR seems to have done it:
[](https://github.com/tighten/laravel-mix-jigsaw/pull/25/commits/3e3a4fa312f879d6346fe9d21201e6c7bcbfe2ac)
