### ISSUE TITLE
Docs build process not working

### ISSUE THREAD

**Issue by gn-pmcgeough** [tighten/jigsaw#680]
This usually isn't a problem because I take a theme/template and dump it in the assets and reference it directly but...

When following the instructions the assets dont seem to compile as described in the docs.

Instructions followed:
`composer require tightenco/jigsaw` > `./vendor/bin/jigsaw init` > `npm install` > `npm run dev`
Running `./vendor/bin/jigsaw build` also has the same resulting code below.

You can see the link to the assets will try to find a root file and the canonical link doesn't fix it. 

![Screenshot 2023-02-21 at 11 39 28](https://user-images.githubusercontent.com/81236323/220335228-4f255289-0fc1-4e4f-8858-627a12615130.png)

I tried playing with the mix line in the blade so the output would be `"./assets/build/css....` but adding ./ made it appear `"/./assets/build/css....`

I am not sure the tailwind works as expected either. Running through the docs I get about  500 lines in my output main.css this in contrast with the blog template with over 1100 lines. I've copied tailwind package versions, tailwind config and webpack pages from blog to standard but still only showing the 500 or so lines of out put.

Any ideas on both scenarios I have here. Thanks you.

**Comment by bakerkretzmar** [comment]
What's the issue here exactly? Those links are valid and should work if your compiled assets are present at that path.
